//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAP.Core.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EAP.Core.ResourceFile.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;&quot;en&quot;&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;&quot;UTF-8&quot;&quot;&gt;
        ///    &lt;meta name=&quot;&quot;viewport&quot;&quot; content=&quot;&quot;width=device-width, initial-scale=1.0&quot;&quot;&gt;
        ///    &lt;title&gt;Action on Advertisement&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table width=&quot;&quot;100%&quot;&quot; border=&quot;&quot;0&quot;&quot; cellspacing=&quot;&quot;0&quot;&quot; cellpadding=&quot;&quot;0&quot;&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;&quot;center&quot;&quot;&gt;
        ///                &lt;table width=&quot;&quot;600&quot;&quot; border=&quot;&quot;0&quot;&quot; cellspacing=&quot;&quot;0&quot;&quot; cellpadding=&quot;&quot;0&quot;&quot; bgcolor=&quot;&quot;#f4f4f4&quot;&quot;&gt;
        ///                    &lt;tr&gt;
        ///                        &lt;td align=&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ActionOnAdvertisement {
            get {
                return ResourceManager.GetString("ActionOnAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Password Reset Request&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;h1&gt;Password Reset Request&lt;/h1&gt;&lt;p&gt;We received a request to reset your account password.&lt;/p&gt;&lt;p&gt;If you did not make this request, please disregard this message.&lt;/p&gt;&lt;p&gt;To reset your password, please follow the link below:&lt;/p&gt;&lt;a href=http:/localhost:5288/Login/CreatePassword?token={userLogin.Token}&amp;email={userLogin.Email}&gt;Reset Password&lt;/a&gt;&lt;p&gt;If you have any questions or need further assistance, please contact your manager or HR department.&lt;/p&gt;&lt;p&gt;Tha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
    }
}
